# Generated by Django 5.0.14 on 2026-09-11 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(default="USA", max_length=50)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_cycle_used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "total_distance_miles",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "total_driving_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "total_duration_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("COMPLIANT", "Compliant"),
                            ("VIOLATION", "Violation"),
                        ],
                        default="COMPLIANT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_origin",
                        to="trips.location",
                    ),
                ),
                (
                    "dropoff_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_dropoff",
                        to="trips.location",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_pickup",
                        to="trips.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                ("duration", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "rest_type",
                    models.CharField(
                        choices=[
                            ("30_MIN_BREAK", "30-Minute Break"),
                            ("10_HOUR_SLEEPER", "10-Hour Sleeper Berth"),
                            ("34_HOUR_RESTART", "34-Hour Restart"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.location"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rest_stops",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuelStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                (
                    "duration",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.location"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_stops",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "off_duty_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "sleeper_berth_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "driving_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "on_duty_not_driving_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "total_miles",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("remarks", models.JSONField(default=list)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[("VALID", "Valid"), ("INVALID", "Invalid")],
                        default="VALID",
                        max_length=20,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DRIVING", "Driving"),
                            ("PICKUP", "Pickup"),
                            ("DROPOFF", "Dropoff"),
                            ("FUEL", "Fuel"),
                            ("REST_BREAK", "Rest Break"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                            ("OFF_DUTY", "Off Duty"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "duty_status",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "Off Duty"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                            ("DRIVING", "Driving"),
                            ("ON_DUTY_NOT_DRIVING", "On Duty (Not Driving)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "distance_miles",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("reason", models.TextField()),
                ("sequence", models.IntegerField(default=1)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trips.location",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "start_time"],
            },
        ),
    ]
